#!/bin/bash

# MIT No Attribution
# 
# Copyright 2025 KIVoP
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE kivop;
	GRANT ALL PRIVILEGES ON DATABASE kivop TO vapor;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname 'kivop' <<-EOSQL
	CREATE TABLE IF NOT EXISTS "_fluent_migrations" ("id" UUID PRIMARY KEY, "name" TEXT NOT NULL, "batch" BIGINT NOT NULL, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, CONSTRAINT "uq:_fluent_migrations.name" UNIQUE ("name"));
	CREATE TABLE IF NOT EXISTS "_fluent_enums" ("id" UUID PRIMARY KEY, "name" TEXT NOT NULL, "case" TEXT NOT NULL, CONSTRAINT "uq:_fluent_enums.name+_fluent_enums.case" UNIQUE ("name", "case"));
	
	CREATE GROUP services;
	GRANT CREATE, CONNECT ON DATABASE kivop TO GROUP services;

	GRANT SELECT, REFERENCES, INSERT, UPDATE, DELETE ON TABLE "_fluent_migrations" TO GROUP services;
	GRANT SELECT, REFERENCES, INSERT, UPDATE, DELETE ON TABLE "_fluent_enums" TO GROUP services;
	GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA public TO GROUP services;
	GRANT USAGE, CREATE ON SCHEMA public TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR ROLE services IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;

	-- Service-Users
	CREATE USER ${POLL_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${POLL_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;
	CREATE USER ${AI_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${AI_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;
	CREATE USER ${RIDE_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${RIDE_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;
	CREATE USER ${POSTER_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${POSTER_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;
	CREATE USER ${NOTIFICATIONS_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${NOTIFICATIONS_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;
	CREATE USER ${AUTH_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${AUTH_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;
	CREATE USER ${MEETING_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${MEETING_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;
	CREATE USER ${CONFIG_SERVICE_POSTGRES_USERNAME} WITH PASSWORD '${CONFIG_SERVICE_POSTGRES_PASSWORD}' IN GROUP services;

	-- Service-User-Privileges
	ALTER DEFAULT PRIVILEGES FOR USER ${POLL_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR USER ${AI_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR USER ${RIDE_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR USER ${POSTER_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR USER ${NOTIFICATIONS_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR USER ${AUTH_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR USER ${MEETING_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
	ALTER DEFAULT PRIVILEGES FOR USER ${CONFIG_SERVICE_POSTGRES_USERNAME} IN SCHEMA public GRANT SELECT, REFERENCES ON TABLES TO GROUP services;
EOSQL
